language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

git:
  depth: 3

after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("OpenEphysLoader")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("OpenEphysLoader")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
