site_name:        OpenEphysLoader.jl
repo_url:         https://github.com/galenlynch/OpenEphysLoader.jl
site_description: A set of tools to load data written by the OpenEphys GUI
site_author:      galenlynch

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
